### ISSUE TITLE
The trash button sometimes add an alternate choice

### ISSUE THREAD

**Issue by mstp** [etienne/dialog-edit#11]
Behavior witnessed on second node.

**Comment by etienne** [comment]
Celui-là j'ai pas réussi à le reproduire, je ne sais pas si c'est parce que je l'ai accidentellement réglé ou parce que c'est juste rare. Tu me diras si jamais tu le revois!

**Comment by mstp** [comment]
@etienne Pour une configuration comme dans l'image ci-dessous, le bouton de corbeille du deuxième noeud lui ajoute autant de choix alternatifs qu'il y a de choix alternatifs dans le noeud qui le suit.
![issue #11](https://user-images.githubusercontent.com/8077759/102302063-34ad1e80-3f26-11eb-94f8-91c4823940f2.PNG)

**Comment by etienne** [comment]
Malade! Merci, avec ça je devrais être capable de le régler.
