### ISSUE TITLE
It seems impossible to add or remove characters in a branch

### ISSUE THREAD

**Issue by mstp** [etienne/dialog-edit#9]

**Comment by etienne** [comment]
En fait, la liste des personnages est dynamique; normalement, si tu tapes "Pouet" dans un node, "Pouet" devrait s'ajouter au menu déroulant. Si tu effaces tous les nodes avec le personnage Pouet, il devrait disparaître du menu.

Je l'ai fait comme ça pour ajouter et enlever facilement des personnages, sans avoir à gérer une liste séparée (qui créerait des nouveaux problèmes, comme le fait de devoir gérer le cas où on efface un personnage qui est utilisé dans des nodes).

**Comment by mstp** [comment]
@etienne Ah, intéressant. Je n'avais pas essayé de taper un nouveau nom de personnage. Les personnages sont communs à toutes les branches pour l'instant?

**Comment by etienne** [comment]
Oui exact. Dans le fond, le menu c'est juste un raccourci pour ne pas avoir à taper les noms au complet à chaque fois.
